### ISSUE TITLE
Possible scaling issues with 1.26.1.1

### ISSUE THREAD

**Issue by snwflake** [alex-joens/wot-better-reticle-size#3]
Since the recent update, I have a very strong feeling that the scaling the mod applies is no longer correct.
I do not have screenshot evidence for it however, but the fact that my caliban reticle "fully aimed" roughly covers twice as much area as it did before 1.26.1.

It's gotten to a point where I literally cannot tell what will and what won't hit, because I am so used to the reticle being considerably smaller, that I lost all feel for the "default" reticle.

I don't know if I'm just going mad, or if anyone else may be able to confirm that though.

**Comment by alex-joens** [comment]
I've received a couple of reports for this issue, but I haven't been able to replicate it.

Can you upload your python.log file? And can you share a screenshot of your mod settings page as well?

**Comment by alex-joens** [comment]
Also, are you installing the mod directly from Github or through a modpack?

**Comment by snwflake** [comment]
Sure thing.

![shot_031](https://github.com/user-attachments/assets/0933b4d1-4695-45b7-a7f8-527137dd6f49)

[python.log](https://github.com/user-attachments/files/17438647/python.log)

I installed the mod as part of Aslain's modpack. Will install it standalone from releases and update you on that.

**Comment by snwflake** [comment]
turns out the mod was working fine, the issue was caused by XVM Sight, which has been updated now.
